# Generated by Django 5.2.14 on 2026-05-20 03:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0002_mission_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchMission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_code', models.CharField(blank=True, db_index=True, max_length=36, unique=True)),
                ('title', models.CharField(default='Untitled batch', max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('ready', 'Ready'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_code', models.CharField(blank=True, db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('writing_goal', models.CharField(blank=True, max_length=255)),
                ('default_export_format', models.CharField(choices=[('markdown', 'Markdown'), ('latex', 'LaTeX'), ('align', 'Align'), ('inline', 'Inline')], default='latex', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='formulajob',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formula_jobs', to='formulas.batchmission'),
        ),
        migrations.CreateModel(
            name='FormulaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('formula_code', models.CharField(blank=True, db_index=True, max_length=40, unique=True)),
                ('latex_current', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('auto_ready', 'Auto ready'), ('needs_review', 'Needs review'), ('edited', 'Edited'), ('confirmed', 'Confirmed'), ('exported', 'Exported'), ('rejected', 'Rejected')], default='needs_review', max_length=20)),
                ('quality_score', models.PositiveSmallIntegerField(default=0)),
                ('quality_flags', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_items', to='formulas.batchmission')),
                ('recognition_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formula_item', to='formulas.formulajob')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_items', to='formulas.paperproject')),
            ],
            options={
                'ordering': ['batch', 'sort_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='batchmission',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='formulas.paperproject'),
        ),
        migrations.AddField(
            model_name='formulajob',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formula_jobs', to='formulas.paperproject'),
        ),
    ]
