# Generated by Django 5.2.14 on 2026-05-23 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0003_product_core'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaItemVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latex', models.TextField()),
                ('source', models.CharField(choices=[('ocr', 'OCR'), ('manual', 'Manual'), ('system_correction', 'System correction'), ('export_snapshot', 'Export snapshot')], max_length=32)),
                ('created_by_label', models.CharField(blank=True, max_length=80)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='formulas.formulaitem')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
