# Generated by Django 5.2.14 on 2026-05-23 03:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0004_formulaitemversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_code', models.CharField(blank=True, db_index=True, max_length=36, unique=True)),
                ('title', models.CharField(default='Untitled manuscript', max_length=160)),
                ('root_file_path', models.CharField(default='main.tex', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='formulas.paperproject')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('tex', 'TeX'), ('bib', 'BibTeX'), ('markdown', 'Markdown'), ('text', 'Text')], default='tex', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='formulas.paperdocument')),
            ],
            options={
                'ordering': ['sort_order', 'path', 'created_at'],
                'unique_together': {('document', 'path')},
            },
        ),
    ]
